// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace VidMePortable.Model.Responses
{
    public class GeoFencesResponse
    {
        [JsonProperty("status")]
        public bool Status { get; set; }

        [JsonProperty("geofences")]
        public List<Geofence> Geofences { get; set; }
    }

}
